import { makeStyles, Theme } from "@material-ui/core";
import { primaryColor, primaryTextColor } from "../../../constants/colors";

export default makeStyles((theme: Theme) => ({
  pageContainer: {
    position: "relative",
    display: "flex",
    minHeight: "calc(100vh - 130px)",
    paddingBottom: 30,
  },
  pageHeadSection: {
    width: "100%",
    height: 250,
    backgroundColor: primaryColor,
    position: "absolute",
    zIndex: 0,
  },
  backButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    position: "absolute",
    top: 0,
    left: 0,
    marginLeft: 40,
    marginTop: 40,
    "& span": {
      marginLeft: 10,
      fontSize: 14,
      fontWeight: "bold",
      color: "white",
    },
  },
  customerDetailsSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 100,
    padding: "0 40px",
    width: "100%",
    zIndex: 1,
    "@media (max-width: 780px)": {
      padding: "0 10px",
      margin: 0,
      marginTop: 100,
    },
  },
  customerDetailCard: {
    width: "100%",
    borderRadius: 15,
    backgroundColor: "white",
    boxShadow: "none",
    padding: 20,
    marginBottom: 25,
    "@media (max-width: 400px)": {
      padding: 10,
    },
  },
  cardContents: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    "@media (max-width: 400px)": {
      padding: 0,
      paddingTop: 20,
    },
  },
  customerServicesSection: {
    display: "flex",
    flexDirection: "column",
  },
  customerActionButton: {
    width: 30,
    height: 30,
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    backgroundColor: "#F6F6FB",
    position: "absolute",
    top: 0,
    right: 0,
    marginRight: 10,
  },
  customerName: {
    fontSize: 24,
    fontWeight: "bold",
    color: primaryTextColor,
    marginTop: 20,
  },
  customerDetailPersonalInfoRow: {
    marginTop: 30,
  },
  customerDetailPersonalInfoTextBox: {
    marginLeft: 20,
    display: "flex",
    flexDirection: "column",
  },
  customerDetailPersonalInfoTextTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#B7BBD8",
  },
  customerDetailPersonalInfoTextDesc: {
    fontSize: 14,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  customerContactButton: {
    padding: "10px 25px",
    borderRadius: 10,
    border: "2px solid #E4E6F2",
    margin: "0 20px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    cursor: "pointer",
    marginTop: 30,
    "@media (max-width: 480px)": {
      width: "100%",
      margin: 0,
      marginTop: 20,
      justifyContent: "center",
    },
  },
  customerContactButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: primaryTextColor,
    marginLeft: 15,
  },
  upcomingServicesCardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2DCA73",
    width: "100%",
    textAlign: "left",
  },
  tableContainer: {
    width: "100%",
    overflowX: "auto",
    marginTop: 30,
    boxShadow: "none",
  },
  table: {
    minWidth: 600,
  },
  upComingServicesTableHeader: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#B7BBD8",
  },
  upComingServicesTableHeaderRow: {
    backgroundColor: "#F6F6FB",
    height: 40,
  },
  noDataBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "15px 0",
  },
  noServiceTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: primaryTextColor,
    marginTop: 30,
  },
  servicesHistoryCardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#B7BBD8",
    width: "100%",
    textAlign: "left",
  }
}));
