export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';

export const BUSINESS_INFO = 'BUSINESS_INFO';
export const ADDITIONAL_BUSINESS_INFO = 'ADDITIONAL_BUSINESS_INFO';
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';

export const CUSTOMER_INFO = 'CUSTOMER_INFO';

export const MY_SERVICES = 'MY_SERVICES';
export const ADD_NEW_SERVICE = 'ADD_NEW_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';

export const CUSTOMERS = 'CUSTOMERS';
export const ADD_NEW_CUSTOMERS = 'ADD_NEW_CUSTOMERS';
export const EDIT_CUSTOMERS = 'EDIT_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const SET_USER_NAME_MIDDLE = 'SET_USER_NAME_MIDDLE';
export const SET_COMPANY_INFO = 'SET_COMPANY_INFO';

export const GET_MESSAGES = 'GET_MESSAGES';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_FAILED = 'GET_APPOINTMENTS_FAILED';
export const SEND_MESSAGES = 'SEND_MESSAGES';
export const RECEIVER_ID = 'RECEIVER_ID';
export const GET_CUSTOMER_MESSAGES = 'GET_CUSTOMER_MESSAGES';
export const GET_COMPANY_MESSAGES = 'GET_COMPANY_MESSAGES';
export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_CUSTOMER = 'GET_CONVERSATION_CUSTOMER';

export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
