import googleImage from "../assets/images/login/google.svg";
import linkedinImage from "../assets/images/login/linkedin.svg";

export const myServices = [
  {
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "Lorem Ipsum is simply dummy text of the printing aasfafsdfsafsadfsdfdsasadf",
    category: "rrr",
    pricingType: 1,
    amount: 12,
    companyId: "string",
    photos: [googleImage, linkedinImage, googleImage, googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 1,
    amount: 12,
    companyId: "string",
    photos: [googleImage, linkedinImage, linkedinImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 2,
    amount: 12,
    companyId: "string",
    photos: [googleImage, linkedinImage, linkedinImage, linkedinImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 1,
    amount: 12,
    companyId: "string",
    photos: [googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 2,
    amount: 12,
    companyId: "string",
    photos: [googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 2,
    amount: 12,
    companyId: "string",
    photos: [googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 1,
    amount: 12,
    companyId: "string",
    photos: [linkedinImage, googleImage, googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 1,
    amount: 12,
    companyId: "string",
    photos: [googleImage, linkedinImage, googleImage, googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 2,
    amount: 12,
    companyId: "string",
    photos: [googleImage, googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },{
    id: "123",
    createdAt: "2432",
    updatedAt: "string",
    isDeleted: false,
    name: "dan",
    description: "sdfsafasf adsfasf adsfasdfdsaf",
    category: "rrr",
    pricingType: 2,
    amount: 12,
    companyId: "string",
    photos: [googleImage, googleImage],
    tags: ["sadf", "asdf", "wefew"],
    companyCity: "string",
    companyState: "string",
  },
];
