import { makeStyles } from "@material-ui/core";
import { primaryTextColor, primaryColor, secondaryColor } from "../../../../constants/colors";

export default makeStyles((theme) => ({
  logoText: {
    marginLeft: 15,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  signupTitle: {
    margin: 0,
    marginTop: 40,
    marginBottom: 20,
    color: primaryTextColor,
    fontSize: 36,
    fontWeight: "bold",
    textAlign: "center",
  },
  signupForm: {
    width: 450,
    [theme.breakpoints.down("xs")]: {
      width: "95%",
    },
  },
  inputsRow: {
    width: "100%",
  },
  halfWidthInput: {
    width: "48%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  inputSectionLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  inputErrorMessage: {
    fontSize: 12,
    fontWeight: "bold",
    color: secondaryColor,
  },
  passStrengthMeterContainer: {
    width: "100%",
    marginBottom: 10,
    marginTop: 10,
  },
  passStrengthMeterWrapper: {
    width: "100%",
  },
  passStrengthMeterItem: {
    width: "33%",
    height: 5,
    borderRadius: 20,
    transitionDuration: "0.3s",
  },
  passStrengthText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFD136",
  },
  profileImageWrapper: {
    width: "48%",
    padding: 25,
    borderRadius: 10,
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  profileTypeText: {
    fontSize: 14,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  profileTypeInputsRow: {
    width: "100%",
    marginTop: 15,
    marginBottom: 20,
  },
  termsAndConditionsText: {
    fontSize: 12,
    marginLeft: 12,
    fontWeight: 600,
    "& span": {
      color: primaryColor,
      cursor: "pointer",
    },
  },
  continueButton: {
    width: "100%",
    borderRadius: 10,
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
    border: "none",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 0",
    marginTop: 20,
  },
  backButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    position: "absolute",
    top: 0,
    left: 0,
    marginLeft: 100,
    marginTop: 100,
    "& span": {
      marginLeft: 10,
      fontSize: 14,
      fontWeight: "bold",
      color: primaryTextColor,
    },
    [theme.breakpoints.down("xs")]: {
      marginLeft: 20,
      marginTop: 20,
    },
  },
  stepText: {
    fontSize: 12,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  optionalText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#B7BBD8",
  },
  additionalBusinessTextarea: {
    width: "100%",
    height: 150,
    border: "1px solid #E4E6F2",
    borderRadius: 10,
    marginTop: 15,
    padding: 20,
    resize: "none",
  },
  skipButton: {
    width: "100%",
    borderRadius: 10,
    color: primaryColor,
    fontSize: 14,
    fontWeight: "bold",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 0",
    marginTop: 20,
  },
  companyLogoUploadSection: {
    margin: "15px 0 40px 0",
  },
  companyLogoImage: {
    padding: 20,
    backgroundColor: "#E8EDFF",
    borderRadius: 50,
    border: "5px solid white",
    boxShadow: "4px 2px 20px #E4E6F2",
  },
  supportText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#B7BBD8",
  }, 
  fileInput: {
    display: "none",
  },
  uploadButton: {
    backgroundColor: "white",
    boxShadow: "4px 2px 20px #E4E6F2",
    border: "none",
    padding: "13px 20px",
    borderRadius: 10,
    cursor: "pointer",
  },
  uploadText: {
    fontSize: 12,
    fontWeight: "bold",
    color: primaryColor,
  },
  companyLogoImageItem: {
    width: 90,
    height: 90,
    borderRadius: "100%",
  },
  imageDragArea: {
    padding: "20px 0",
    width: "100%",
    border: "1px dashed #E4E6F2",
    borderRadius: 10,
    marginTop: 15,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  imageDropText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#707070",
    marginTop: 14,
  },
  imageDropTextButton: {
    color: primaryColor,
    cursor: "pointer",
  },
  imageItemWrapper: {
    marginTop: 15,
  },
  imageItem: {
    width: 60,
    height: 45,
    borderRadius: 5,
  },
  imageTitleBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginLeft: 15,
  },
  coverButton: {
    padding: "10px 15px",
    backgroundColor: "#E8EDFF",
    borderRadius: 10,
    cursor: "pointer",
    marginRight: 15,
  },
  deleteButton: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#B7BBD8",
    cursor: "pointer",
  },
  imageTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: primaryTextColor,
  },
  imageProperty: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#B7BBD8",
  },
  coverButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: primaryColor,
  },
  imageItemActionsWrapper: {
    marginLeft: "auto",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  checkedAsCover: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
    borderRadius: 10,
    cursor: "pointer",
    border: "1px solid #E4E6F2",
    padding: "10px 20px",
  },
  checkedAsCoverText: {
    fontSize: 12,
    fontWeight: "bold",
    color: primaryTextColor,
    marginLeft: 10,
  },
}));
